version: '3'
services:
  test:
    build: .
    ports:
      - "8088:8088"
    depends_on:
      - postgres
  postgres:
    image: postgres:12.4
    environment:
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    hostname: postgres
    container_name: postgres_test
